// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
    TELEGRAM_BOT_TOKEN: string;
    SOLANA_PRIVATE_KEY: string;
    RPC_URL: string;
    OPENAI_API_KEY: string;
    ALLORA_API_KEY?: string;
    ALLORA_API_URL?: string;
    PERPLEXITY_API_KEY?: string;
    JUPITER_REFERRAL_ACCOUNT?: string;
    JUPITER_FEE_BPS?: string;
    FLASH_PRIVILEGE?: string;
    HELIUS_API_KEY?: string;
    ETHEREUM_PRIVATE_KEY?: string;
    ELFA_AI_API_KEY?: string;
}
